### ISSUE TITLE
How to apply multiple rules on one inut

### ISSUE THREAD

**Issue by T-Roth** [kettanaito/react-advanced-form#260]
Is there a way to apply multiple rules on one input?  

Something like this?
<Input label="Registration Key" name="authorizedRegistrationKey" value={this.state.authorizedRegistrationKey} onChange={this.handleInputChange} required **_rules={[minLength, maxLength]}_** />

**Comment by kettanaito** [comment]
Hi, @T-Roth.

Let me start from highlighting that RAF encourages functional approach in validation. One of the aspects that brings is that each piece of validation can be a pure function. So you don't even need to keep it in the schema directly (you can just reference the validator function there), and neither you should bind it to the input render.

Now, answering your question.

## Using `Field.props.rule`
It *doesn't* support an array, but it does support a RegExp or a *function*:

```js
const hasCapitalLetter = (value) => /[A-Z]/.test(value)
const hasProperLength = (value, length) => value.length >= length

<Input
  name="firstName"
  rule={({ value, fieldProps, fields, form }) => {
    return hasCapitalLetter(value) && hasProperLength(value, 5)
  }}
  required
/>
```

So the input above accepts a validator function as the value of a `rule` prop. That function must return a boolean, stating that the field's value (or state) is considered valid. Since it's a function, you can use a short circuit as above to call multiple validator functions, which means having multiple rules for the same field.

## Using validation schema

Alternative way is to specify the explicit validation rules in the schema:

```jsx
// validation-rules.js
const rules = {
  name: {
    firstName: {
      capitalLetter: ({ value }) => /[A-Z]/.test(value),
      minLength: ({ value }) => value.length >= 6
    }
  }
}
```

Once this kind of schema is defined, you can pass it as a `rules` prop to `<FormProvider>` (to apply the rules application-wide), or to the individual `<Form>` component (to apply for that specific form). You need to choose *one* of these two options.

For example, let's say that all the fields with the `[name="firstName"]` must abide by that two validators (capitalLetter and minLength). Then we would use `<FormProvider>` to do that:


```jsx
// app/index.js
import React from 'react'
import ReactDOM from 'react-dom'
// import the form provider
import { FormProvider } from 'react-advanced-form'
// import that rules schema defined above
import rules from './validation-rules'

const App = () => (
  <FormProvider rules={rules}>
    <YouAppHere />
  </FormProvider>
)

ReactDOM.render(<App />, document.getElementById('root'))
```

Read more on [multiple validation rules](https://redd.gitbook.io/react-advanced-form/getting-started/validation-rules#multiple-rules) in the documentation.

---

I recommend using the second approach, having a clear validation schema with the named rules. That makes validation declarative and allows you to have custom set of validation messages relative to each named rule (so `capitalLetter` and `minLength` rules can have unique validation errors).

I hope that answers your question.

**Comment by kettanaito** [comment]
This, and many other uses cases are covered in the documentation — [Validation rules](https://redd.gitbook.io/react-advanced-form/validation/rules).

Have you looked into that? If something wasn't clear for you, could you write me what exactly, so I could improve the documentation? Thanks.
