### ISSUE TITLE
How can I disable a submit button until the form is in a valid state?

### ISSUE THREAD

**Issue by T-Roth** [kettanaito/react-advanced-form#261]
How can I disable a submit button until the form is in a valid state?

**Comment by kettanaito** [comment]
## Short answer

There is no way to do that. Moreover, I would recommend you not to do so at the first place. See more detailed answer below.

## Long answer
I see a problem with your requirement UX-wise.

In order to get the form's validity state you need to submit the form. Having "invalid" form with no errors displayed under the fields is a horrible thing to have. Having all fields marked in red when you render the form initially is equally devastating.

React Advanced Form takes a smart approach on this, and any field in a form is neither valid, nor invalid at initial render. This has a long backstory and has proven itself a sensible approach for any use case.

Sorry, at the moment there is no way to do that. This requirement is much more ambiguous conceptually, rather than technically. I don't plan to support this unless it's well thought through. If you have a suggestion of how to achieve your requirement while preserving a good UX, please post it here and we can come up with something.

Thanks.

**Comment by T-Roth** [comment]
I see what your saying and agree that all the fields in a form showing as invalid initially is a bad idea.   

I was thinking that there could be an isValid property on the form that could be checked without triggering the UI to display everything as invalid.

**Comment by kettanaito** [comment]
If you perform `form.submit()` this will validate all fields in the form and mark them correspondingly.

This is **not the recommended**, however, as it is much more evident if you click on submit button, triggering the submit, rather than calling the method directly. But in some cases you may want to do that, I understand.

```jsx
this.form.submit()

<Form ref={form => this.form = form}>
  {/* ... */}
</Form>
```

**Comment by T-Roth** [comment]
I think you misunderstood,  I don't want to initially submit() or call validate() or do anything that would make the UI light up like Christmas before the user has taken any action.   I was just looking for a property on the Form like "isValid" that I could use to toggle the disabled state of a button.  I'm not sure of the inner workings of the Form component to know if what I'm asking for is even possible.  If not then no big deal.

Thanks for your thorough answers they are very helpful.

**Comment by kettanaito** [comment]
@T-Roth Sorry, this is not possible now. As I explained, making this happen may have a somewhat ambiguous behavior. Internally, we solve this be having three values of what is a boolean flag for field's validity:

* true - field is valid
* false - field is invalid
* null - explicitly, field is neither

But this is not suitable for API, since most of people will rely on `!form.state.isValid`, which will produce falsy result in case of explicit `null` (initial render).

I will keep this requirement in mind, but can't offer any solution at the moment.
